/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.1
 * Generated at: 2024-07-03 05:44:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import model.TblProductocl3;

public final class ListadoProductos_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/Users/Usuario/Documents/CIBERTEC%20INFORMATICA/LPII_CL3_ESPINOZAMINAYACHRISTIAN/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/LPII_CL3_ESPINOZAMINAYACHRISTIAN/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153403082000L));
    _jspx_dependants.put("jar:file:/C:/Users/Usuario/Documents/CIBERTEC%20INFORMATICA/LPII_CL3_ESPINOZAMINAYACHRISTIAN/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/LPII_CL3_ESPINOZAMINAYACHRISTIAN/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153403082000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1719028653465L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write(" \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Listado de Productos</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body bgcolor=\"#c5dec9\">\r\n");
      out.write("<h1  align=\"center\">Listado de Productos registrados en la BD</h1>\r\n");
      out.write("\r\n");
      out.write("<h2 align=\"center\">\r\n");
      out.write("<a href=\"FormRegistrarProducto.jsp\" style=\"text-decoration: none; color blue;\">Registrar Producto</a></h2>\r\n");
      out.write("\r\n");
      out.write("<table border=\"2\" align=\"center\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td>Nombre</td>\r\n");
      out.write("<td>Precio Venta</td>\r\n");
      out.write("<td>Precio Compra</td>\r\n");
      out.write("<td>Estado</td>\r\n");
      out.write("<td>Descripción</td>\r\n");
      out.write("\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");


List<TblProductocl3> listadoproducto=(List<TblProductocl3>)request.getAttribute("listadodeproductos");

//aplicamos una condicion..

if(listadoproducto!=null){

	//aplicamos un bucle for..

	for(TblProductocl3 lis:listadoproducto){

		
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\t\t<td>");
      out.print(lis.getNombrecl3() );
      out.write("</td>\r\n");
      out.write("\t\t<td>");
      out.print(lis.getPrecioventacl3() );
      out.write("</td>\r\n");
      out.write("\t\t<td>");
      out.print(lis.getPreciocompcl3() );
      out.write("</td>\r\n");
      out.write("\t\t<td>");
      out.print(lis.getEstadocl3() );
      out.write("</td>\r\n");
      out.write("\t\t<td>");
      out.print(lis.getDescripcl3() );
      out.write("</td>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("   ");
 
	}  //fin del bucle for...
	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("   ");
 
} //fin de la condicion ...


      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
